baseURL = 'https://bruno-ah-um.github.io/'
defaultContentLanguage = "en"
languageCode = 'en-us'
title = 'Bruno Ah Um'
theme = 'dream'

[pagination]
  pagerSize = 10

[params]
lightTheme = "emerald"
darkTheme = "forest"

author = "Bruno Caballero"
description = "Lead Software Engineer | JVM Specialist | Qiskit Advocate"
headerTitle = "Bruno Caballero"
motto = "JVM Runtimes, Compilers & Quantum Computing"
avatar = "img/avatar.png"

siteStartYear = 2026

# Options
showTableOfContents = true
showPrevNextPost = true

[params.advanced]
customCSS = ["css/custom.css"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = false
    noClasses = true
    style = "monokai"
